export {
  createVault,
  unlockVault,
  lockVault,
  isUnlocked,
  isVaultAvailable,
  getDecryptedPayload,
  persistPayload,
  exportVault,
  importVault,
  changePassphrase,
  deleteVault,
  tryAutoUnlock,
  type VaultPayload,
} from './vault'
